---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bgg-ing
  labels:
    name: bgg-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: bggappv1-svc
      port:
        number: 80
  rules:
  # - host: bgg-139.59.216.208-nip.io
  # - host: bggv1
    - http:
        paths:
        - path: /v1
          pathType: Prefix
          backend:
            service:
              name: bggappv1-svc
              port:
                number: 80
        - path: /v2
          pathType: Prefix
          backend:
            service:
              name: bggappv2-svc
              port:
                number: 80
  