apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme

resources:
- ../base

commonLabels:
  tenant: acme

namePrefix: acme-

configMapGenerator:
- name: wordpress-db-cm 
  behavior: create
  literals:
  - MYSQL_DATABASE=acmedb
  - MYSQL_USER=user

secretGenerator:
- name: wordpress-db-secret 
  behavior: create
  literals:
  - MYSQL_ROOT_PASSWORD=changeit
  - MYSQL_PASSWORD=123456

replacements:
- source:
    kind: Service
    name: wordpress-db-svc
    fieldPath: metadata.name
  targets:
  - select:
      kind: StatefulSet
      name: wordpress-sts
    fieldPaths:
    - spec.template.spec.containers.[name=wordpress].env.[name=WORDPRESS_DB_HOST].value

patches:
- path: ./fqdn.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: wordpress-ing
