---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  labels:
    name: bggapp-secret
type: Opaque
data:
  db_password: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  selector:
    matchLabels:
      name: bggapp-po
  replicas: 3
  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
    spec:
      containers:
      - name: bggapp
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: BGG_DB_USER
          value: root
        - name: BGG_DB_HOST
          value: bggdb-svc
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bggapp-secret
              key: db_password
        ports: 
        - containerPort: 3000 
        livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
        readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
 
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-po
  ports:
  - port: 80
    targetPort: 3000
