---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-bear-cm
  labels:
    name: dov-bear-cm
data:
  INSTANCE_NAME: myapp
---
apiVersion: v1
kind: Secret
metadata:
  name: dov-bear-secret
  labels:
    name: dov-bear-secret
type: Opaque
data:
  db_password: Y2hhbmdlaXQ=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
spec:
  selector:
    matchLabels:
      name: dov-bear-po
  replicas: 3
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
    spec:
      containers:
      - name: dov-bear
        image: chukmunnlee/dov-bear:v2
        imagePullPolicy: IfNotPresent
        env:
        # - name: INSTANCE_NAME
          # value: pod-dov-bear
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef: 
                fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: dov-bear-cm
        - secretRef:
            name: dov-bear-secret
        ports: 
        - containerPort: 3000 
        livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
 
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
spec:
  type: LoadBalancer
  selector:
    name: dov-bear-po
  ports:
  - port: 80
    targetPort: 3000

