apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
spec:
  selector:
    matchLabels:
      name: bggdb-po
  replicas: 1
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
    spec:
      containers:
      - name: bggdb
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
 
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bgg-database-po
  ports:
  - port: 3306
    targetPort: 3306
